### PR TITLE
Added useUnifiedTopology to valid option names

### PR DESCRIPTION
**Pull request by sam-simpleclick**

### CODE REVIEW

**Review by ihabZhaika — CHANGES_REQUESTED** [review]
Hey,
Remove the package-lock file

**Review by ihabZhaika — APPROVED** [review]
Tested this change and it do work, @v4l3r10  can you merge ?

**Comment by sam-simpleclick** [comment]
@ihabZhaika i've removed the package-lock file

**Comment by ihabZhaika** [comment]
> @ihabZhaika i've removed the package-lock file

Yep i saw, will need to wait for the maintainer to merge the change

**Comment by ihabZhaika** [comment]
> @ihabZhaika i've removed the package-lock file

In meantime if you want you can use this until he merges the patch [if will in the near time]
https://www.npmjs.com/package/cache-manager-mongodb-fix

**Pull request merged**
