### PR TITLE
Update deps and fix index creation for new mongodb versions

### LINKED ISSUE #6: Can't make it work
I can't manage how to make it work, 

I tried this piece of code: 

```
const cacheManager = require('cache-manager')
const mongoStore = require('cache-manager-mongodb')

const mongoCachePromise = () => {
  return new Promise((resolve) => {
    const mongoCache = cacheManager.caching({
      store: mongoStore,
      uri: 'mongodb://localhost:27017/lisa',
      options: {
        collection: 'cacheManager',
        compression: false,
        poolSize: 5,
        auto_reconnect: true
      },
      createCollectionCallback: () => {
        console.log('done creating collection');
        return resolve(mongoCache);
      },
    });
  });
};

mongoCachePromise().then((mongoCache) => {
  return mongoCache.get('test', () => {
    console.log('test')
    return 'ok'
  });
});

```

And I get: 

```
the options [collection] is not supported
the options [compression] is not supported
the options [auto_reconnect] is not supported
Error During Indexes creation
```
I also try with host and port under options but it's also say `is not supported`

Node cache manager v2.4.0
Node cache manager mongo v0.1.7
Node v7

### PR DESCRIPTION
**Pull request by jaumard**
Fix #6

### CODE REVIEW

**Comment by v4l3r10** [comment]
Thx!

**Comment by jaumard** [comment]
No problem :) can you publish a new version with this fix please ?

**Comment by v4l3r10** [comment]
I will do new release tomorrow, i need to done some changes to code for the Promises support.

**Comment by jaumard** [comment]
That would be awesome :) I wanted to do it in this PR but wasn't sure how to do it to keep callback support :/ I'll look on how you've done it :D

**Comment by jaumard** [comment]
@v4l3r10 any new on the release of this ? don't think it has been done yet

**Pull request merged**
